Version: 1

Settings:
  Economy: false
  PriceOfTheBlockExpanse: 1000
  
DefaultAreaSettings:
  DefaultEnterMessage: "&2Prave jsi vstoupil do oblasti &5<New_Area>&2, kterou vlastni &5<Owner>."
  DefaultLeaveMessage:  "&2Prave jsi opustil oblast &5<Old_Area>&2."
  AreaFlags:
    build: false
    use: false
    container: false
  MaxHeight: 255
  MinHeight: 32
  MaxLength: 161
  MinLength: 32
  MaxWidth: 161
  MinWidth: 32